server:
  port: 8080

jwt:
  secret: syllabicate31231412312321314231231241241231231234124123
  expiration: 86400000

spring:
  datasource:
    url: jdbc:oracle:thin:@DongHung:1521:orcl
    username: MANAGE_BOOK
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.OracleDialect
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy



